# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{incurve}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stefano Verna @weLaika"]
  s.date = %q{2010-07-30}
  s.description = %q{InCurve provides some handy helper methods for your Rails app, letting you easily inline your CSS code.}
  s.email = %q{stefano.verna@welaika.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "incurve.gemspec",
     "lib/incurve.rb",
     "lib/incurve/string_premailer.rb",
     "lib/incurve/view_helpers.rb",
     "test/helper.rb",
     "test/test_incurve.rb"
  ]
  s.homepage = %q{http://github.com/welaika/incurve}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Inline that damn CSS in your mail views.}
  s.test_files = [
    "test/helper.rb",
     "test/test_incurve.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<premailer>, [">= 1.5.4"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<premailer>, [">= 1.5.4"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<premailer>, [">= 1.5.4"])
  end
end

